import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import "@/styles/globals.css";

const font = Roboto_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <p>Layout Detalhe</p>
      {children}
    </>
  );
}
